services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

volumes:
  web:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/web/'
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/database/'

networks:
  inception:
    driver: bridge
